Wf restructure
CenterForMedicalGeneticsGhent/nf-cmgg-preprocessing pull request #33
Opened 2022-10-24 10:35 UTC by matthdsm

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
  - [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/CenterForMedicalGeneticsGhent/nf-cmgg-preprocessing/tree/master/.github/CONTRIBUTING.md)
  - [ ] If necessary, also make a PR on the CenterForMedicalGeneticsGhent/nf-cmgg-preprocessing _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

2022-10-26 11:22 UTC, nvnieuwk requested changes

2022-10-26 11:22 UTC, nvnieuwk commented on .github/workflows/nf-test.yml
> +          nf-test test ${GITHUB_WORKSPACE}/tests/${{ matrix.test }}.test
```suggestion
          nf-test test tests/${{ matrix.test }}.test
```

This should fix some tests

2022-10-27 07:50 UTC, nvnieuwk commented
![Very nice](https://media.giphy.com/media/10uEX5kfeodYgo/giphy.gif)

2022-10-27 08:11 UTC, matthdsm commented
Still not nice enough 😑 Alignment works, cram compression does not...

2022-12-08 13:53 UTC, merged